/*
DECLARE

CURSOR C1 IS 
SELECT ISBN10, BRANCH_ID, COPIES_NO
FROM PROJECT1_BOOK_COPIES_LOAD
WHERE COPIES_NO > 0
ORDER BY 1;

VARC1 C1%ROWTYPE;
V_COPIES NUMBER;

BEGIN
    OPEN C1;
    LOOP
        FETCH C1 INTO VARC1;
        EXIT WHEN C1%NOTFOUND;
        
        V_COPIES := VARC1.COPIES_NO;
        
        FOR I IN 1..V_COPIES LOOP
            INSERT INTO PROJECT1_BOOK_COPIES
            VALUES(BOOK_ID_SEQ.NEXTVAL, VARC1.ISBN10, VARC1.BRANCH_ID);
        END LOOP;    
    END LOOP;
    CLOSE C1;
END;
*/

